name: Build AssetLoader ARM64 Linux BIN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-arm64-bin:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: apt update (mit Retry)
        run: |
          for i in 1 2 3; do
            sudo apt-get update && break || sleep 10
          done

      - name: Install dependencies
        run: sudo apt-get install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross libcurl4-openssl-dev:arm64

      - name: Build AssetLoader (Cross)
        run: |
          make clean || true
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AssetLoader-bin
          path: build/AssetLoader.bin
